version: '3'
services:
  redis:
    image: redis:4

  db:
    image: postgres:9.6
    restart: always
    env_file:
      - env/postgres.env

  initdb:
    build: .
    command: ["sh/wait-for-postgres.sh", "db", "airflow", "initdb"]
    depends_on:
      - db
    env_file:
      - env/airflow.env

  webserver:
    build: .
    command: ["sh/wait-for-migrations.sh", "db", "airflow", "webserver"]
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/home/airflow/dags
      - ./plugins:/home/airflow/plugins
    env_file:
      - env/airflow.env
    depends_on:
      - initdb

  scheduler:
    build: .
    command: ["sh/wait-for-migrations.sh", "db", "airflow", "scheduler"]
    volumes:
      - ./dags:/home/airflow/dags
      - ./plugins:/home/airflow/plugins
    env_file:
      - env/airflow.env
    depends_on:
      - initdb

  worker:
    build: .
    command: ["sh/wait-for-migrations.sh", "db", "airflow", "worker"]
    volumes:
      - ./dags:/home/airflow/dags
      - ./plugins:/home/airflow/plugins
    env_file:
      - env/airflow.env
    depends_on:
      - initdb
      - redis
